plugin: aws_ec2
aws_access_key: # Enter your aws access key
aws_secret_key: # Enter the secret acccess key of your aws
regions:
  - # Use Region of Resources
keyed_groups:
  - key: tags
    prefix: tags 
compose: 
  ansible_host: private_ip_address