---

- name: Service Deployment
  hosts: all
  user: ubuntu
  become: yes
  gather_facts: True

  tasks:  

      # Next we git clone the Terabyte Repo to access the necessary files 
    - name: Git Clone Terabyte Repo 
      git: 
        repo: https://github.com/Angelo512/Terabyte-CIT481-Senior-Project.git
        dest: /TerabyteCIT481
        force: yes

    # Replacing the default index.html file with our personalized one
    - name: Switching out the default index.html with our groups personalized index.html
      command: mv /var/www/html/TerabyteCIT481/Project1/Ansible/index.html /var/www/html/index.html


    ## ADDING MORE FILES TO /VAR/WWW/HTML

    # Replacing the default index.html file with our personalized one
    - name: Switching out the default index.html with our groups personalized index.html
      command: mv /var/www/html/TerabyteCIT481/Project1/Ansible/SimpleCalendar.html /var/www/html/SimpleCalendar.html


    # Replacing the default index.html file with our personalized one
    - name: Switching out the default index.html with our groups personalized index.html
      command: mv /var/www/html/TerabyteCIT481/Project1/Ansible/SimpleCalendar.css /var/www/html/SimpleCalendar.css


    # Replacing the default index.html file with our personalized one
    #- name: Switching out the default index.html with our groups personalized index.html
     # command: mv /var/www/html/TerabyteCIT481/Project1/path/to/file /var/www/html/nameoffile

    ## ETC. 


      # Finally we can start the apache web service 
    - name: Starting The Web Server
      service: name=apache2 state=started