---

- name: Web Server Configuration
  hosts: all
  user: ubuntu
  become: yes
  gather_facts: True

  tasks:

    # First we install the apache web server to the ec2 instance(s) BUT we avoid starting it 
    - name: Installing The Apache Web Server
      apt: 
        name: apache2 
        state: present
      environment: # module allows us to install apache but without starting it immediately 
        RUNLEVEL: 1

      # Next we install git 
    - name: Installing git 
      apt: name=git state=present